/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import dominio.ControladorSemaforos;
import dominio.Semaforo;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author alumnoFI
 */
public class frmSemaforos extends javax.swing.JFrame {
    private ControladorSemaforos modelo;
    private Timer timer;
    /**
     * Creates new form frmSemaforos
     */
    public frmSemaforos() {
        initComponents();
    }
    
    public frmSemaforos(ControladorSemaforos unModelo) {
        initComponents();
        this.modelo = unModelo;
        this.cargarSemaforos();
        timer = new javax.swing.Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {        
                Semaforo unSemaforo = (Semaforo)lstSem.getSelectedValue();
                modelo.cambiarLuz(unSemaforo);
                refrescarLuces(unSemaforo);
            }
        });
        timer.stop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRojo = new javax.swing.JTextField();
        txtAmarillo = new javax.swing.JTextField();
        txtVerde = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        scrSem = new javax.swing.JScrollPane();
        lstSem = new javax.swing.JList();
        btnCambiar = new javax.swing.JButton();
        chkAuto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtRojo.setEditable(false);

        txtAmarillo.setEditable(false);

        txtVerde.setEditable(false);

        jLabel1.setText("Lista de Semaforos");

        scrSem.setToolTipText("");

        lstSem.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstSemValueChanged(evt);
            }
        });
        scrSem.setViewportView(lstSem);

        btnCambiar.setText("Cambiar Luz");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        chkAuto.setText("Automatico");
        chkAuto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkAutoStateChanged(evt);
            }
        });
        chkAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAmarillo)
                    .addComponent(txtRojo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtVerde))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(scrSem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnCambiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(scrSem)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkAuto))
                    .addComponent(txtVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        Semaforo unSemaforo = (Semaforo)this.lstSem.getSelectedValue();
        this.modelo.cambiarLuz(unSemaforo);
        this.refrescarLuces(unSemaforo);
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void lstSemValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstSemValueChanged
        Semaforo unSemaforo = (Semaforo)this.lstSem.getSelectedValue();
        this.refrescarLuces(unSemaforo);
        this.btnCambiar.setEnabled(true);
        this.chkAuto.setSelected(false);
        this.timer.stop();
    }//GEN-LAST:event_lstSemValueChanged

    private void chkAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAutoActionPerformed
        if(this.chkAuto.isSelected()){
            this.timer.start();
            this.btnCambiar.setEnabled(false);
        }
        else {
            this.timer.stop();
            this.btnCambiar.setEnabled(true);
        }
    }//GEN-LAST:event_chkAutoActionPerformed

    private void chkAutoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkAutoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAutoStateChanged

    public void refrescarLuces(Semaforo unSemaforo){
        this.txtVerde.setBackground(Color.white);
        this.txtAmarillo.setBackground(Color.white);
        this.txtRojo.setBackground(Color.white);
        if(unSemaforo.getEstado() == 0) this.txtVerde.setBackground(Color.green);
        if(unSemaforo.getEstado() == 1) this.txtAmarillo.setBackground(Color.yellow);
        if(unSemaforo.getEstado() == 2) this.txtRojo.setBackground(Color.red);
    }
    
    private void cargarSemaforos(){
        this.modelo.agregarSemaforo("aaa");
        this.modelo.agregarSemaforo("bbb");
        this.modelo.agregarSemaforo("ccc");
        this.lstSem.setListData(this.modelo.getLstSemaforos().toArray());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSemaforos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSemaforos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSemaforos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSemaforos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSemaforos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JCheckBox chkAuto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList lstSem;
    private javax.swing.JScrollPane scrSem;
    private javax.swing.JTextField txtAmarillo;
    private javax.swing.JTextField txtRojo;
    private javax.swing.JTextField txtVerde;
    // End of variables declaration//GEN-END:variables
}
